version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://api:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - api
