import type { DashboardPayload } from "@market-copilot/shared";

type AIInsightsPanelProps = {
  dashboard: DashboardPayload;
};

export function AIInsightsPanel({ dashboard }: AIInsightsPanelProps) {
  const biasStyles =
    dashboard.aiInsight.bias === "Bullish"
      ? "border-accent/30 bg-accent/10 text-accent"
      : dashboard.aiInsight.bias === "Bearish"
        ? "border-rose/30 bg-rose/10 text-rose"
        : "border-slate-400/20 bg-white/5 text-slate-200";

  return (
    <section className="panel animate-rise p-5">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="section-title">AI decision assistant</p>
          <h2 className="mt-2 text-xl font-semibold text-white">Decision support</h2>
        </div>
        <div className={`rounded-full border px-3 py-1 text-xs font-semibold ${biasStyles}`}>
          {dashboard.aiInsight.bias}
        </div>
      </div>

      <p className="mt-4 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 text-slate-300">
        {dashboard.aiInsight.summary}
      </p>

      <div className="mt-5 space-y-4">
        <div>
          <h3 className="text-sm font-semibold text-slate-100">Why it thinks this</h3>
          <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-400">
            {dashboard.aiInsight.reasoning.map((item) => (
              <li key={item} className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3">
                {item}
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h3 className="text-sm font-semibold text-slate-100">Catalysts</h3>
          <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-400">
            {dashboard.aiInsight.catalysts.map((item) => (
              <li key={item} className="rounded-2xl border border-accent/10 bg-accent/5 px-4 py-3">
                {item}
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h3 className="text-sm font-semibold text-slate-100">Risks</h3>
          <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-400">
            {dashboard.aiInsight.risks.map((item) => (
              <li key={item} className="rounded-2xl border border-rose/10 bg-rose/5 px-4 py-3">
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="mt-5 rounded-2xl border border-gold/20 bg-gold/10 p-4 text-xs leading-5 text-gold">
        {dashboard.aiInsight.disclaimer} Output generated by {dashboard.aiInsight.generatedBy}.
      </div>
    </section>
  );
}
